In [5]:
import numpy as np

In [7]:
from numpy.random import randint as ri          #to fixed the number of generated numbers

In [9]:
np.random.seed(25)
ri(1,100,(5,6))

array([[ 5, 63, 91, 16, 62, 24],
       [45, 51,  9, 29,  5, 90],
       [32, 70,  2, 40,  4, 89],
       [56,  4, 85, 46,  4,  2],
       [23, 32, 49, 48, 74, 17]])

In [17]:
np.random.seed(100)
M = ri(1,100,25).reshape(5,5)

In [19]:
M

array([[ 9, 25, 68, 88, 80],
       [49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35],
       [25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28]])

In [21]:
np.sort(M)

array([[ 9, 25, 68, 80, 88],
       [11, 49, 53, 95, 99],
       [15, 35, 54, 67, 99],
       [16, 17, 25, 59, 61],
       [ 3, 10, 28, 87, 94]])

In [25]:
np.sort(M, axis=0)     #vertically

array([[ 9, 11, 61,  3, 17],
       [10, 16, 68, 15, 28],
       [25, 25, 87, 53, 35],
       [49, 67, 95, 59, 80],
       [54, 94, 99, 88, 99]])

In [27]:
np.sort(M, axis=1)      #horizontically

array([[ 9, 25, 68, 80, 88],
       [11, 49, 53, 95, 99],
       [15, 35, 54, 67, 99],
       [16, 17, 25, 59, 61],
       [ 3, 10, 28, 87, 94]])

In [31]:
#conditional selection

a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [33]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [35]:
a[a > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
a[a < 10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [41]:
a[a%2 !=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [43]:
a[a==5]   #collection of similar elements. upcasting

array([5])

In [45]:
a[a<5]

array([1, 2, 3, 4])

In [49]:
a[a%2 !=0] = 0
a

array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,  0,
       18,  0, 20])

In [51]:
a = np.array([1,2,3,4,5,2])
print(a)

[1 2 3 4 5 2]


In [53]:
a.ndim #number of dimention

1

In [55]:
a.shape

(6,)

In [57]:
x=np.where(a==2)   # index return
x

(array([1, 5], dtype=int64),)

In [59]:
np.where(a==3)

(array([2], dtype=int64),)

In [61]:
b = np.array([1,2,3,4,5,6])
print(b)

[1 2 3 4 5 6]


In [63]:
np.where(b<4)

(array([0, 1, 2], dtype=int64),)

In [65]:
np.where(b>5)

(array([5], dtype=int64),)

In [67]:
#Practice

a=np.array([[1,2,7],[3,4,5]])
a

array([[1, 2, 7],
       [3, 4, 5]])

In [73]:
a.shape    #row and column

(2, 3)

In [75]:
a[1,1]

4

In [77]:
a=np.array([[1,2,3],[4,5,6]])
a.shape=(1,6)
a

array([[1, 2, 3, 4, 5, 6]])

In [81]:
a[0,4]     #index is 0 in single list

5

In [89]:
a=np.arange(36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [91]:
a.shape

(36,)

In [95]:
b=a.reshape(3,4,3)
b
#b.ravel()

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [97]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [101]:
a.itemsize   # size of integer in memory bites  ---- 4bytes (length of each element of array in bytes)

4

In [103]:
a=np.array([1.0,2,3,4])
a.itemsize

8

In [105]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [107]:
a

array([[1, 2],
       [3, 4]])

In [109]:
b

array([[5, 6],
       [7, 8]])

In [113]:
np.concatenate((a,b),axis=0) #axis=0 means rows vstack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [115]:
np.concatenate((a,b),axis=1) #axis=1 means column vstack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [119]:
a=np.arange(12)
np.split(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [121]:
a=np.array([[1,2,3],[4,5,6]])
np.resize(a, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [123]:
a=np.array([[1,2,3],[4,5,6]])
np.append(a, [[7,8,9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
np.sqrt(100)

10.0