In [7]:
import numpy as np

In [9]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [15]:
a = np.array([1,2.0,3])
print(a)
print(type(a))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [17]:
a = np.array([1,'2',3])
print(a)
print(type(a))

['1' '2' '3']
<class 'numpy.ndarray'>


In [19]:
a = np.array([1,'2',3.0])
print(a)
print(type(a))

['1' '2' '3.0']
<class 'numpy.ndarray'>


In [ ]:
#String ---------- Upcasting
float
int

In [23]:
#More than one dimention
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [31]:
#Minimum dimention
a=np.array([1,2,3,4,5], ndmin = 2)
print(a)
print(a.shape)

[[1 2 3 4 5]]
(1, 5)


In [29]:
a=np.array([1,2,3,4,5])
print(a.shape)

(5,)


In [35]:
a=np.array([1,2,3,4,5], ndmin = 4)
print(a)
print(a.shape)

[[[[1 2 3 4 5]]]]
(1, 1, 1, 5)


In [37]:
#Shape

a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [41]:
#Sizes
a=np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [43]:
#Reshape

a=np.array([[1,2,3],[4,5,6]])
print(a)
b=a.reshape(3,2)
print(b)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [49]:
#Return a new array of specified size and type, filled with zeros.

x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [51]:
x=np.zeros(5,dtype=int)
print(x)

[0 0 0 0 0]


In [53]:
x=np.zeros((5,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [55]:
#Ones function

x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [57]:
x=np.ones([2,2],dtype=int)
print(x)

[[1 1]
 [1 1]]


In [59]:
x=np.eye(2)  # For identity matrix
print(x)

[[1. 0.]
 [0. 1.]]


In [63]:
#Empty

x=np.empty([3,2],dtype=int)
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [65]:
#Asarray

#convert list to ndarray  --- fewer parameters

x=[1,2,3]
print(type(x))
a=np.asarray(x)
print(type(a))
print(a)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3]


In [67]:
#Data type is provided

x=[1,2,3]
a=np.asarray(x,dtype=float)
print(a)

[1. 2. 3.]


In [69]:
#ndarray from tuple

x=(1,2,3)
a=np.asarray(x)
print(a)

[1 2 3]


In [73]:
#ndarray from list of tuple

x=[(1,2,3),(4,5)]
a=np.asarray(x)
print(a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [75]:
x=[(1,2,3),(4,5,6)]
a=np.asarray(x)
print(a)

[[1 2 3]
 [4 5 6]]


In [77]:
#Arange

#an array of evenly spaced numbers

a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [79]:
a=np.arange(24)
a.ndim

1

In [83]:
x=np.arange(5,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [85]:
x=(np.arange(10,22,2)).reshape(2,3)
print(x)

[[10 12 14]
 [16 18 20]]


In [89]:
#linspace

x=np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [91]:
#end point set to false for excluding last value

x=np.linspace(10,20,5, endpoint=False)
print(x)

[10. 12. 14. 16. 18.]


In [93]:
#find retstep value 

x=np.linspace(10,50,8, retstep=True)
print(x)

(array([10.        , 15.71428571, 21.42857143, 27.14285714, 32.85714286,
       38.57142857, 44.28571429, 50.        ]), 5.714285714285714)


In [95]:
x=np.linspace(10,20,8, retstep=True)
print(x)

(array([10.        , 11.42857143, 12.85714286, 14.28571429, 15.71428571,
       17.14285714, 18.57142857, 20.        ]), 1.4285714285714286)


In [103]:
#Create matrix in Numpy

#In numpy , we use the np.array() function to create  a matrix. For example,

#create a 2 into 2 matrix

matrix1 = np.array([[1,3],[5,7]])
print("2*2 matrix:\n",matrix1)

#create a 3 into 3 matrix

matrix2 = np.array([[2,3,5],
                    [7,14,21],
                   [1,3,5]])
print("\n3*3 matrix:\n",matrix2)

2*2 matrix:
 [[1 3]
 [5 7]]

3*3 matrix:
 [[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]


In [105]:
#Create a 3 into 3 matrix

a=np.array([[2,3,5],[7,14,21],[1,3,5]])

print(a)
print()

b= np.array([[2,3,5],[7,14,21],[1,3,5]])

print(b)
print()

c=a+b
print(c)

[[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]

[[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]

[[ 4  6 10]
 [14 28 42]
 [ 2  6 10]]


In [107]:
#Multiply -- create two matrices

matrix1=np.array([[1,3],[5,7]])

matrix2=np.array([[2,6],[4,8]])

#calculate the dot product of the two matrices
result=np.dot(matrix1,matrix2)
print("matrix1 * matrix2: \n",result)          #1*2+3*4    1*6+3*8

matrix1 * matrix2: 
 [[14 30]
 [38 86]]


In [109]:
#Transpose

matrix1=np.array([[1,3],[5,7]])
print(matrix1)
print()

#get transpose of matrix1
result=np.transpose(matrix1)
print(result)

[[1 3]
 [5 7]]

[[1 5]
 [3 7]]
