In [3]:
#Random number generation         #data create karta hai numpy,statistics - sin , cos

import numpy as np

In [33]:
#generate random integer from 0 to 9
random_number = np.random.randint(0, 10)

print(random_number)

2


In [39]:
from numpy import random  #2nd way - random is module in numpy

random_number = random.randint(0, 10)
print(random_number)

7


In [83]:
#generate random float in numpy

#float - restriction  -- value generate 0 to 1

random_number = np.random.rand()
print(random_number)

0.7641193470729591


In [85]:
#generate 1D array of random integers between 0 to 9

integer_array = np.random.randint(0,10,5)
print("ID Random Integer Array:\n",integer_array)

ID Random Integer Array:
 [2 6 3 3 5]


In [87]:
#generate 1D array of 5 random numbers between 0 and 1

float_array=np.random.rand(5)
print("\n1D Random Float Array:\n",float_array)


1D Random Float Array:
 [0.15343039 0.45034266 0.37937066 0.60448369 0.00442274]


In [89]:
#generate 2D array of shape (3,4) with random integers

result = np.random.randint(0,10, (3,4))
print("\n2D Random Integer Array:\n",result)


2D Random Integer Array:
 [[2 8 6 4]
 [2 5 8 8]
 [6 8 7 5]]


In [91]:
#create an array of integers from 1 to 5

array1 = np.array([1,20,3,40,5])

#choose a random number from array1

random_choice = np.random.choice(array1)

print(random_choice)

3


In [101]:
x= 2*(np.ones(5))
print(x)

[2. 2. 2. 2. 2.]


In [107]:
a=np.array([[12,23,34],[45,56,67],[67,78,89]])
print(a)
print()
print(np.diag(a))    #output as diagnal value

[[12 23 34]
 [45 56 67]
 [67 78 89]]

[12 56 89]


In [109]:
a=np.eye(5) #identity matrix -- diagnally 1 come in matric form
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [111]:
a=5*np.eye(5)
print(a)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [115]:
x=np.diag([4,5,6,7,8,9])     #diagnal matrix
print(x)

[[4 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 6 0 0 0]
 [0 0 0 7 0 0]
 [0 0 0 0 8 0]
 [0 0 0 0 0 9]]


In [117]:
a = np.random.randint(1,20,10)
print(a)

[16 15  5  9  4  8 14  6  9 15]


In [119]:
x=np.random.rand(5)
print(x)

[0.06612581 0.09274737 0.07953938 0.8974895  0.03917542]


In [121]:
y=np.random.rand(4,4)
print(y)

[[0.90562525 0.72427741 0.50696154 0.53854409]
 [0.4228218  0.40733845 0.83859686 0.90434672]
 [0.27360827 0.91025197 0.70975717 0.93657417]
 [0.27006824 0.50783359 0.89956617 0.6817812 ]]


In [131]:
a= np.random.randn(5)
print(a)

[ 0.49618859 -0.27371194 -0.18368144 -0.24483794 -0.54560851]


In [133]:
#Accessing through SLICING

x = np.array([[1,2,3,9,10], [12,34,4,5,6], [65,76,7,8,9], [12,34,4,5,6], [65,76,7,8,9]])
print(x)

[[ 1  2  3  9 10]
 [12 34  4  5  6]
 [65 76  7  8  9]
 [12 34  4  5  6]
 [65 76  7  8  9]]


In [135]:
x[1:3,2:4]     # :: row and column

array([[4, 5],
       [7, 8]])

In [137]:
print(x[1:3,2:4])

[[4 5]
 [7 8]]


In [145]:
print(x[1:4,2:4])

[[4 5]
 [7 8]
 [4 5]]


In [147]:
#numpy.hstack() function

#horizontically stack numpy array using numpy.hstack()

x = np.array((3,5,7))
print(x)
print()
y = np.array((5,7,9))
print(y)
print()
print(np.hstack((x,y)))

[3 5 7]

[5 7 9]

[3 5 7 5 7 9]


In [149]:
x = np.array([[3], [5], [7]])
print(x)
print()
y = np.array([[5], [7], [9]])
print(y)
print()
print(np.hstack((x,y)))

[[3]
 [5]
 [7]]

[[5]
 [7]
 [9]]

[[3 5]
 [5 7]
 [7 9]]


In [151]:
#numpy.vstack() function

#vertically stack numpy array using numpy.hstack()

x = np.array((3,5,7))
print(x)
print()
y = np.array((5,7,9))
print(y)
print()
print(np.vstack((x,y)))

[3 5 7]

[5 7 9]

[[3 5 7]
 [5 7 9]]


In [153]:
x = np.array([[3], [5], [7]])
print(x)
print()
y = np.array([[5], [7], [9]])
print(y)
print()
print(np.vstack((x,y)))

[[3]
 [5]
 [7]]

[[5]
 [7]
 [9]]

[[3]
 [5]
 [7]
 [5]
 [7]
 [9]]


In [155]:
#Shallow and Deep Copy

l=[1,"2",3,4,5]
l1=l
l1

[1, '2', 3, 4, 5]

In [157]:
l1[2]=100
l1

[1, '2', 100, 4, 5]

In [159]:
l

[1, '2', 100, 4, 5]

In [161]:
#copy method
l=[1,2,3,4,5]
l

[1, 2, 3, 4, 5]

In [165]:
l2=l.copy()
l2

[1, 2, 3, 4, 5]

In [167]:
l2[1]=100
l2

[1, 100, 3, 4, 5]

In [169]:
l

[1, 2, 3, 4, 5]

In [171]:
#Nested list        -- copy method doesnt work in nested list (because id address are different)
 
l=[[1,2,3],[4,56]]
l

[[1, 2, 3], [4, 56]]

In [173]:
l2=l.copy()
l2

[[1, 2, 3], [4, 56]]

In [179]:
l2[0][2]=100
l2

[[1, 2, 100], [4, 56]]

In [181]:
l

[[1, 2, 100], [4, 56]]

In [191]:
#Deep copy

import copy

In [193]:
l=[[1,2,3],[4,56]]

In [197]:
l2=copy.deepcopy(l)
l2

[[1, 2, 3], [4, 56]]

In [199]:
l2[0][2]=100

In [201]:
l2

[[1, 2, 100], [4, 56]]

In [203]:
l

[[1, 2, 3], [4, 56]]

In [205]:
print(id(l2))

1500868636608


In [207]:
print(id(l))

1500868687488


In [209]:
a = np.random.randint(1,10,(3,3))
print(a)

[[3 9 6]
 [2 7 6]
 [9 2 5]]


In [211]:
a = np.array([[3,3,2],[6,9,4],[5,5,8]])
a

array([[3, 3, 2],
       [6, 9, 4],
       [5, 5, 8]])

In [213]:
a.shape

(3, 3)

In [215]:
np.sum(a)

45

In [217]:
np.sum(a,axis=0) #columns -- vertical

array([14, 17, 14])

In [219]:
np.sum(a,axis=1) #rows -- horizontal

array([ 8, 19, 18])

In [221]:
np.min(a)

2

In [223]:
np.max(a)

9

In [225]:
np.min(a,axis=1) #horizontal

array([2, 4, 5])

In [227]:
np.max(a,axis=1) #horizontal

array([3, 9, 8])

In [229]:
np.min(a,axis=0) #vertical

array([3, 3, 2])

In [231]:
np.max(a,axis=0) #vertical

array([6, 9, 8])